sales_group:
  outputs:
    prod:
      type: redshift
      threads: 2
      host: "{{ env_var('DBT_REDSHIFT_HOST') }}"
      port: "{{ env_var('DBT_REDSHIFT_PORT') | int }}"
      dbname: "{{ env_var('DBT_REDSHIFT_DATABASE') }}"
      schema: "{{ env_var('DBT_REDSHIFT_SCHEMA') }}"
      user: "{{ env_var('DBT_REDSHIFT_USER') }}"
      password: "{{ env_var('DBT_REDSHIFT_PASSWORD') }}"
      connect_timeout: "{{ env_var('DBT_REDSHIFT_TIMEOUT') | int }}"
      ra3_node: true
    ci:
      type: redshift
      threads: 2
      host: "{{ env_var('DBT_REDSHIFT_HOST') }}"
      port: "{{ env_var('DBT_REDSHIFT_PORT') | int }}"
      dbname: "{{ env_var('DBT_REDSHIFT_DATABASE') }}"
      schema: "{{ env_var('DBT_REDSHIFT_SCHEMA') }}"
      user: "{{ env_var('DBT_REDSHIFT_USER') }}"
      password: "{{ env_var('DBT_REDSHIFT_PASSWORD') }}"
      connect_timeout: "{{ env_var('DBT_REDSHIFT_TIMEOUT') | int }}"
      ra3_node: true      
  target: prod