select
    {# zindex as "Index of the invalid record", #}
    bu_crusr as "User who created the object",
    bu_crdat as "Date on which the object was created",
    bu_birthdt as "Date of Birth of Business Partner",
    bu_birthpl as "Birthplace of business partner",
    bu_namep_l as "Last name of business partner (person)",
    bu_namep_f as "First name of business partner (person)",
    bu_nameor1 as "Name 1 of organization",
    bu_nameor2 as "Name 2 of organization",
    bu_nameor3 as "Name 3 of organization",
    bu_nameor4 as "Name 4 of organization",
    ad_title as "Form-of-Address Key",
    bu_sort1 as "Search Term 1 for Business Partner",
    bu_sort2 as "Search Term 2 for Business Partner",

    ltrim(bu_partner,'0') as "Business Partner Number",
            
    bu_type as "Business Partner Category",
    bu_group as "Business Partner Grouping",
    bu_bpext as "Business Partner Number in External System",
    bu_bpkind as "Business Partner Type",
    bu_bkvid as "Bank details ID",
    bu_banks as "Bank Country Key",
    bu_bankk as "Bank Key",
    bu_bankn as "Bank Account Number",
    bu_bkont as "Bank Control Key",
    bu_bkref as "Reference Details for Bank Details",
    bu_koinh as "Account Holder Name",
    bu_bankaccname as "Name of Bank Account",
    bu_relnr as "BP Relationship Number",
    bu_partner_2 as "Business Partner Number_2",
    bptaxtype as "Tax Number Category",
    bptaxnum as "Business Partner Tax Number",
    ukm_limit_zero as "Limit Is Zero",
    ukm_credit_sgmnt as "Credit Segment",
    ukm_credit_limit as "Credit Limit",
    ukm_sgm_currency as "Credit Segment Currency",
    land1 as "Country/Region Key",
    regiogroup as "Regional structure grouping",
    ad_strspp1 as "Street 2",
    ad_strspp2 as "Street 3",
    ad_strspp3 as "Street 4",
    ad_lctn as "Street 5",
    ad_street as "Street",
    regio as "Region (State, Province, County)",
    kdgrp as "Customer Group",
    bzirk as "Sales District",
    waers_v02d as "Currency",
    ktgrd as "Account Assignment Group for this customer",
    dzterm as "Terms of payment key",
    dwerk_ext as "Delivering Plant (Own or External)",
    vkbur as "Sales office",
    vkgrp as "Sales group",
    kvgr1 as "Customer group 1",
    kvgr2 as "Customer group 2",
    podkz as "Relevant for POD processing",
    vkorg as "Sales Organization",
    spart as "Division",
    vtweg as "Distribution Channel",
    dzuawa as "Key for sorting according to assignment numbers",
    akont as "Reconciliation Account in General Ledger",
    dzahls as "Block Key for Payment",
    dzterm_2 as "Terms of payment key 2",
    hbkid as "Short Key for a House Bank",
    bukrs as "Company Code",
    fdgrv as "Planning Group",
    name1 as "Name1",
    landx50 as "Country Name",
    ad_titletx as "Title text",
    bu_name1tx as "Full Name tx1",
    val_text as "Short Text for Fixed Values",
    bu_text40 as "Description",
    landx50_2 as "Country Name 2",
    bu_text40_2 as "Description bu 2",
    bu_name1tx_2 as "Full Name tx2",
    text50 as "Text Field",
    bezei20 as "Description bzi20",
    vtxtk as "Name",
    bztxt as "Name of the district",
    ltext as "Long Text",
    bezei20_2 as "Description 2",
    bezei20_3 as "Description 3",
    bezei20_4 as "Description 4",
    bezei20_5 as "Description 5",
    val_text_2 as "Short Text for Fixed Values 2",
    vtxtk_2 as "Name 2",
    vtxtk_3 as "Name 3",
    vtxtk_4 as "Name 4",
    txt30 as "Text",
    text1_zun as "Description of the Sort Key",
    textl_008 as "Explanation of the Reason for Payment Block",
    ltxt1 as "Description ltx1",
    butxt as "Name of Company Code or Company",
    val_text_3 as "Short Text for Fixed Values 3",
    ukm_credit_sgmnt_txt as "Name of Credit Segment",
    
    ltrim(kunn2,'0') as "Customer number of business partner",

    knref as "Customer description of partner (plant, storage location)",
    parvw as "Partner Function",
    vtxtk_5 as "Name 5",
    name1_gp as "Name 1",
    dzwels as "List of Respected Payment Methods",
    ad_smtpadr as "E-Mail Address",
    full_adress as "Text, 255 Characters full adress",
    ad_street + ad_strspp3 + ad_lctn + ad_strspp1 + ad_strspp2 as full_address,
    zadd as "Text, 255 Characters zzadd",
    zstore as "Text, 255 Characters",
    takld as "Tax classification for customer",
    kverm as "Memo",
    ad_tlnmbr1 as "First telephone no.: dialling code+number",
    ukm_check_rule_txt as "Name of Check Rule",
    ukm_risk_class_txt as "Name of Risk Class",
    check_rule as "Rule for Credit Check",
    risk_class as "Risk Class",
    aufsd_kna1 as "Central order block for customer",
    aufsd_knvv as "Customer order block"
    
from {{ ref("food_stg_sap_s4__tbl_ztt_zsdc0016") }}
