with renamed as (
    select 
        db,
        "do" as _do,
        perpost,
        batnbr,
        "status" as _status,
        trantype,
        account,
        sub,
        trandate,
        descr,
        unitdesc,
        qty_so,
        qty_in,
        unitprice,
        attackqty,
        curyattackprice,
        km,
        dgvc,
        curytransportfee,
        tiendhang,
        "tiền phí giống + trọng lượng vượt" as tienphigiong_trongluongvuot,
        "tổng thành tiền" as tongthanhtien,
        name,
        custid,
        invoiceno,
        sophieuxuat,
        slsperid,
        "code reporting" as code_reporting,
        projectid,
        "tổng trọng lượng" as tongtrongluong,
        "miền" as region
    from {{ source("farm_excel_pnl", "farm_sales") }}
),

cast_farmsales as (
    select
        db,
        _do,
        perpost::varchar,
        batnbr::varchar,
        _status,
        trantype,
        account::varchar,
        sub,
        trandate,
        descr,
        unitdesc,
        qty_so,
        qty_in,
        unitprice,
        attackqty,
        curyattackprice,
        km,
        dgvc,
        curytransportfee,
        tiendhang,
        tienphigiong_trongluongvuot,
        tongthanhtien,
        name,
        custid,
        invoiceno,
        sophieuxuat,
        slsperid,
        code_reporting,
        projectid,
        tongtrongluong,
        region
    from renamed
)

select * from cast_farmsales