{{ config(materialized="table") }}

select
    db::varchar,
    so::varchar,
    "do"::varchar,
    perpost::varchar,
    batnbr::varchar,
    status::varchar,
    trantype::varchar,
    account::varchar,
    sub::varchar,
    trandate::timestamp,
    invtid::varchar,
    descr::varchar,
    unitdesc::varchar,
    qty_so::double precision,
    qty::double precision,
    qty_in::double precision,
    unitprice::double precision,
    tranamt::double precision,
    name::varchar,
    custid::varchar,
    invoiceno::varchar,
    sophieuxuat::varchar,
    slsperid::varchar,
    salesperson::varchar,
    crtd_user::varchar,
    baseprice::double precision,
    contractprice::double precision,
    shipaddr::varchar,
    shipviaid::varchar,
    bigi_qty::integer,
    bigi_kg::integer,
    promotion_desc::varchar,
    siteid::varchar,
    brid::varchar,
    lineref::varchar,
    shipperlineref::varchar,
    serino::varchar,
    attackid::varchar,
    attackqty::double precision,
    curyattackprice::double precision,
    curylineamt::double precision,
    curytransportfee::double precision,
    curyattackamt::double precision,
    curyextamt::double precision,
    discountamt::double precision,
    ttsauck::double precision,
    tienvat::double precision,
    tiendhang::double precision
from {{ source("farm_excel_sales", "master_data_adj") }}
